version: 2.1

executors:
  conan_executor:
    docker:
      - image: conanio/gcc12-ubuntu18.04
    working_directory: ~/project


jobs:
  build_fcdk:
    executor: conan_executor
    steps:
      - checkout

      - run:
          name: Install Conan
          command: |
            pip install --user conan==2.15.0
            export PATH=/home/conan/.local/bin:$PATH
            conan profile detect
            conan --version
            conan install $PWD --build=missing

      - run:
          name: Configure Conan
          command: |
            conan profile detect
            conan remote add conancenter https://center.conan.io


workflows:
  version: 2.1
  build:
    jobs:
      - build_fcdk
