version: 2
jobs:
  gcc-7:
    build:
      docker:
        - image: conanio/gcc7
      steps:
        - checkout
        - run:
            name: Build Conan package
            command: |
              sudo pip install --upgrade conan
              conan user
              conan create $PWD user/channel

workflows:
  version: 2
  build:
    jobs:
      - gcc-7
